export enum MembershipTier {
  ASSOCIATE = 'ASSOCIATE',
  FULL = 'FULL',
  CORPORATE = 'CORPORATE'
}

export enum ProgramType {
  FOUNDATION = 'FOUNDATION',
  PRACTITIONER = 'PRACTITIONER',
  ADVANCED_PRACTITIONER = 'ADVANCED_PRACTITIONER',
  TEST_PREP = 'TEST_PREP',
  INTERNSHIP = 'INTERNSHIP',
  CORPORATE = 'CORPORATE'
}

export enum CaseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  AWAITING_PARTIES = 'AWAITING_PARTIES',
  MEDIATOR_SELECTION = 'MEDIATOR_SELECTION',
  MEDIATOR_ASSIGNED = 'MEDIATOR_ASSIGNED',
  SCHEDULED = 'SCHEDULED',
  IN_MEDIATION = 'IN_MEDIATION',
  SETTLEMENT_REACHED = 'SETTLEMENT_REACHED',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED'
}
