export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  CASE_MANAGER = 'CASE_MANAGER',
  MEDIATOR_VERIFICATION_OFFICER = 'MEDIATOR_VERIFICATION_OFFICER',
  CONTENT_EDITOR = 'CONTENT_EDITOR',
  PROGRAM_MANAGER = 'PROGRAM_MANAGER',
  MEDIATOR = 'MEDIATOR',
  PRACTITIONER = 'PRACTITIONER',
  STUDENT = 'STUDENT',
  CORPORATE_ADMIN = 'CORPORATE_ADMIN',
  CORPORATE_MEMBER = 'CORPORATE_MEMBER',
  COMMUNITY_MEMBER = 'COMMUNITY_MEMBER'
}

export interface UserSummary {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  roles: UserRole[];
  status: 'ACTIVE' | 'SUSPENDED' | 'PENDING_VERIFICATION';
  createdAt: string;
}
